version: '2'
services:
    myhip-app:
        image: myhip
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://myhip-mariadb:3306/myhip
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    myhip-mariadb:
        extends:
            file: mariadb.yml
            service: myhip-mariadb
